apiVersion: v1
annotations: service.beta.kubernetes.io/azure-load-balancer-internal":"true"
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

